TILE_SIZE = 18

SIMULATION_SPEED = 1

MIN_SPEED = 200 // SIMULATION_SPEED
MAX_SPEED = 400 // SIMULATION_SPEED

MIN_REPRODUCTION_RATE = 25
MAX_REPRODUCTION_RATE = 35

MATURE_AGE = 40
MAX_AGE = MAX_REPRODUCTION_RATE * 3
