TILE_SIZE = 18

SIMULATION_SPEED = 5

MIN_SPEED = 200 // SIMULATION_SPEED
MAX_SPEED = 400 // SIMULATION_SPEED

MIN_REPRODUCTION_RATE = 25
MAX_REPRODUCTION_RATE = 35

MIN_MASS = 20
MAX_MASS = 200


MIN_STRENGTH = 1
MAX_STRENGTH = 200

MATURE_AGE = 40
MAX_AGE = MAX_REPRODUCTION_RATE * 3

SCAV_PENALTY = 2
OMNI_PENALTY = 5
PREDATOR_PENALTY = 1
HERB_PENALTY = 2

NUTRITION_MUTATE_PROBABILITY = 0.01

STRENGTH_PENALTY = 2
SPEED_PENALTY = 2
MASS_PENALTY = 2

DEFAULT_ENERGY = 50000

PLANT_PROBABILITY = 0.9

MIN_PLANT_SIZE = 1
MAX_PLANT_SIZE = 10

PLANT_ENERGY = 1000
CORPSE_ENERGY = 1000
